//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolsCore.Properties.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamietnuť.
        /// </summary>
        public static string Global_Abort {
            get {
                return ResourceManager.GetString("Global_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorovať.
        /// </summary>
        public static string Global_Ignore {
            get {
                return ResourceManager.GetString("Global_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Global_OK {
            get {
                return ResourceManager.GetString("Global_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opakovať.
        /// </summary>
        public static string Global_Retry {
            get {
                return ResourceManager.GetString("Global_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áno.
        /// </summary>
        public static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tlačidlá formulárov.
        /// </summary>
        public static string NameAppFontSetting_Buttons {
            get {
                return ResourceManager.GetString("NameAppFontSetting_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dáta v tabuľkách.
        /// </summary>
        public static string NameAppFontSetting_ChartData {
            get {
                return ResourceManager.GetString("NameAppFontSetting_ChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadpisy v tabuľkách.
        /// </summary>
        public static string NameAppFontSetting_ChartHeaders {
            get {
                return ResourceManager.GetString("NameAppFontSetting_ChartHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisy formulárov.
        /// </summary>
        public static string NameAppFontSetting_Labels {
            get {
                return ResourceManager.GetString("NameAppFontSetting_Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string NameAppFontSetting_Menu {
            get {
                return ResourceManager.GetString("NameAppFontSetting_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavový riadok.
        /// </summary>
        public static string NameAppFontSetting_StateRow {
            get {
                return ResourceManager.GetString("NameAppFontSetting_StateRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okraj.
        /// </summary>
        public static string NameColorSettings_Border {
            get {
                return ResourceManager.GetString("NameColorSettings_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string NameColorSettings_Box {
            get {
                return ResourceManager.GetString("NameColorSettings_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tlačidlo.
        /// </summary>
        public static string NameColorSettings_Button {
            get {
                return ResourceManager.GetString("NameColorSettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvýraznenie.
        /// </summary>
        public static string NameColorSettings_Highlight {
            get {
                return ResourceManager.GetString("NameColorSettings_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisok.
        /// </summary>
        public static string NameColorSettings_Label {
            get {
                return ResourceManager.GetString("NameColorSettings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Značka (v RadioButton a v CheckBox).
        /// </summary>
        public static string NameColorSettings_Mark {
            get {
                return ResourceManager.GetString("NameColorSettings_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string NameColorSettings_Panel {
            get {
                return ResourceManager.GetString("NameColorSettings_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string RError {
            get {
                return ResourceManager.GetString("RError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informácia.
        /// </summary>
        public static string RInfo {
            get {
                return ResourceManager.GetString("RInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka.
        /// </summary>
        public static string RQuestion {
            get {
                return ResourceManager.GetString("RQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornenie.
        /// </summary>
        public static string RWarning {
            get {
                return ResourceManager.GetString("RWarning", resourceCulture);
            }
        }
    }
}
